### ISSUE TITLE
Tests on Sauce Labs are shown as failing. Problem?

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#81] opened 2018-02-23 01:50 UTC
The `README` states that we run our tests on Sauce Labs, which is correct, but it might be a bit confusing that our build badge on Travis is green, but everything on Sauce Labs is in red and will always be since the tests are in fact written to fail and a successful test should fail in the correct way :)

![screenshot from 2018-02-23 02-49-19](https://user-images.githubusercontent.com/308049/36574084-3e457746-1844-11e8-9cef-5a97336de362.png)

Can we do something about this? Maybe just write something beneath the image?

**Comment by vweevers** [comment] 2018-02-23 08:08
Duplicate of https://github.com/airtap/airtap/issues/27#issuecomment-366503722? This matrix replaces an outdated zuul screenshot, but because of the red, I thought it better to put back a screenshot.

**Closed** 2018-02-23 09:04 UTC
Labels: discussion
